site_name: Mi proyecto
nav:
  - Home: index.md
  - About: about.md

theme:
  features:
    - content.action.edit
    - content.action.view
    - navigation.tabs
    - navigation.tabs.sticky
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'blue'
  font: 
    text: 'Roboto'

repo_url: 'https://github.com/jibanezmico/MkDocs'
repo_name: 'GitHub'
edit_uri: 'edit/main/docs/'
